// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   int32
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Entry struct {
	ID        int64
	AccountID int64
	// can be positive or negative
	Amount    int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// must be positive
	Amount    int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
